### PR TITLE
Create gh-pages branch via GitHub

### PR DESCRIPTION
**Pull request by bortkiewicz**
Seriously? THAT is the current gh-pages????

### CODE REVIEW

**Comment by hanyuone** [comment]
That's not really our priority now.

**Comment by bortkiewicz** [comment]
I wonder when the wiki is going to be created.

**Comment by hanyuone** [comment]
Ummm... do you understand the syntax of Logicode well? If you do, then you can write the Wiki page, if you want.

**Comment by hanyuone** [comment]
Yup, we'll merge this for now!

**Comment by bortkiewicz** [comment]
Thanks.

**Comment by hanyuone** [comment]
Could you help with writing the wiki, @testitem?

**Comment by bortkiewicz** [comment]
Sure.

**Comment by bortkiewicz** [comment]
Uh... did you disable the wiki? I can't open it. If i click it it redirects me to the code.

P.S. When are you going to add me as a collaborator (whoever made this repo)?

**Comment by bortkiewicz** [comment]
see #18

**Comment by bortkiewicz** [comment]
At least I'm guessing this is what you are doing when you aren't on ways to not make money organization

**Comment by bortkiewicz** [comment]
I'm currently working on a Visual Studio Code extension for Logicode

**Pull request merged**
