### PR TITLE
Upload Notepad++ syntax file

### PR DESCRIPTION
**Pull request by schas002**

### CODE REVIEW

**Comment by bortkiewicz** [comment]
Do we need this???

**Comment by somebody1234** [comment]
@schas002 I'll merge it after you remove redundant lines

**Comment by schas002** [comment]
Which lines are redundant?

**Comment by bortkiewicz** [comment]
Comments?

**Comment by schas002** [comment]
Yeah, comments.

**Comment by bortkiewicz** [comment]
What is this to do anyways???

**Comment by somebody1234** [comment]
@schas002 Also the empty lines like `<Keywords name="Numbers, prefix1"></Keywords>` look like they
're redundant too

**Comment by schas002** [comment]
:arrow_up: but idk could it work w/o these lines.

**Comment by somebody1234** [comment]
@schas002 Can't you just test it to see if it works?

**Comment by schas002** [comment]
Okay, I'll test it.

**Comment by hanyuone** [comment]
@schas002 Is the testing done?

**Comment by schas002** [comment]
Not yet.

**Comment by schas002** [comment]
In fact, I didn't even _do_ the testing. :frowning:

**Comment by bortkiewicz** [comment]
Is this PR abandoned?

**Comment by testitem** [comment]
_**Is this PR abandoned?**_

**Comment by bortkiewicz** [comment]
# _**IS THIS PULL REQUEST ABANDONED?**_

**Comment by schas002** [comment]
Now it is. :cry:

**Pull request closed without merging**
