### PR TITLE
Split files

### PR DESCRIPTION
**Pull request by hanyuone**

### CODE REVIEW

**Comment by bortkiewicz** [comment]
Good. Now i can close that ticket...

**Comment by somebody1234** [comment]
I don't think this is a good idea, putting things in different files is only going to slow loading down, plus it's still pretty short right now

**Comment by bortkiewicz** [comment]
@DerpfacePython please REVERT the commit via Github Desktop so that merging works :(

**Comment by bortkiewicz** [comment]
Can we artificially merge this?

**Pull request closed without merging**
